spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: tiger
    url: jdbc:mysql://localhost:3306/mybatis?serverTimezone=UTC
    type: org.springframework.jdbc.datasource.DriverManagerDataSource

